In [1]:
import numpy as np
import pandas as pd
import warnings
train_file = r'C:\Users\harsh\OneDrive\Desktop\train_data_set.csv'
test_file = r'C:\Users\harsh\OneDrive\Desktop\test_data_set.csv'
mt_train = pd.read_csv(train_file)
mt_test = pd.read_csv(test_file)

In [2]:
mt_train.columns.nunique()
mt_test.columns.nunique()

11

In [3]:
mt_test.head()

,created_at,entry_id,current,voltage,vibration,temperature,latitude,longitude,relay_status,humidity,failure
0,2022-04-05T13:30:41+05:30,1,2.223148,223.14752,0,37.36264,NaN,NaN,0,56,NaN
1,2022-04-05T13:30:58+05:30,2,2.213905,224.07919,0,37.48474,NaN,NaN,0,56,NaN
2,2022-04-05T13:31:14+05:30,3,2.333177,223.81500,0,37.60684,NaN,NaN,0,56,NaN
3,2022-04-05T13:31:30+05:30,4,2.097085,224.11105,0,37.24054,NaN,NaN,0,56,NaN
4,2022-04-05T13:31:47+05:30,5,2.249357,223.86400,0,37.36264,NaN,NaN,0,55,NaN

In [4]:
mt_train.head()

,created_at,entry_id,current,voltage,vibration,temperature,latitude,longitude,relay_status,humidity,failure
0,2022-03-15T17:17:51+05:30,1,1.938089,238.64746,0,37.11844,NaN,NaN,1,25,yes
1,2022-03-15T17:18:07+05:30,2,2.352603,215.62500,0,37.36264,NaN,NaN,0,25,no
2,2022-03-15T17:18:24+05:30,3,3.654926,152.06055,0,37.24054,NaN,NaN,0,46,no
3,2022-03-15T17:18:41+05:30,4,2.420011,195.74707,0,37.11844,NaN,NaN,0,26,no
4,2022-03-15T17:19:00+05:30,5,2.632627,177.10449,0,37.11844,NaN,NaN,0,26,no

In [5]:
mt_train['data']='train'
mt_test['data']='test'
mt_all = pd.concat([mt_train,mt_test],axis=0)
print(mt_train)
print(mt_test)
print(mt_all)

                    created_at  entry_id   current    voltage  vibration  \
0    2022-03-15T17:17:51+05:30         1  1.938089  238.64746          0
1    2022-03-15T17:18:07+05:30         2  2.352603  215.62500          0
2    2022-03-15T17:18:24+05:30         3  3.654926  152.06055          0
3    2022-03-15T17:18:41+05:30         4  2.420011  195.74707          0
4    2022-03-15T17:19:00+05:30         5  2.632627  177.10449          0
..                         ...       ...       ...        ...        ...
754  2022-04-05T13:29:20+05:30       755  2.452396  223.58131          0
755  2022-04-05T13:29:36+05:30       756  2.290720  223.07837          0
756  2022-04-05T13:29:52+05:30       757  2.190200  223.09837          0
757  2022-04-05T13:30:09+05:30       758  2.427122  222.83594          0
758  2022-04-05T13:30:25+05:30       759  1.913182  222.25797          0

     temperature  latitude  longitude  relay_status  humidity failure   data
0       37.11844       NaN        NaN             1        25     yes  train
1       37.36264       NaN        NaN             0        25      no  train
2       37.24054       NaN        NaN             0        46      no  train
3       37.11844       NaN        NaN             0        26      no  train
4       37.11844       NaN        NaN             0        26      no  train
..           ...       ...        ...           ...       ...     ...    ...
754     37.48474       NaN        NaN             0        56      no  train
755     37.11844       NaN        NaN             0        56      no  train
756     37.72894       NaN        NaN             0        56      no  train
757     37.11844       NaN        NaN             0        56      no  train
758     37.97314       NaN        NaN             0        56      no  train

[759 rows x 12 columns]
                    created_at  entry_id   current    voltage  vibration  \
0    2022-04-05T13:30:41+05:30         1  2.223148  223.14752          0
1    2022-04-05T13:30:58+05:30         2  2.213905  224.07919          0
2    2022-04-05T13:31:14+05:30         3  2.333177  223.81500          0
3    2022-04-05T13:31:30+05:30         4  2.097085  224.11105          0
4    2022-04-05T13:31:47+05:30         5  2.249357  223.86400          0
..                         ...       ...       ...        ...        ...
188  2022-04-05T14:45:50+05:30       189  2.447289  211.85481          0
189  2022-04-05T14:46:06+05:30       190  2.425245  212.24246          0
190  2022-04-05T14:46:22+05:30       191  4.281932  238.45860          0
191  2022-04-05T14:46:38+05:30       192  3.826854  401.23560          0
192  2022-04-05T14:46:54+05:30       193  4.181952  250.38970          0

     temperature  latitude  longitude  relay_status  humidity  failure  data
0       37.36264       NaN        NaN             0        56      NaN  test
1       37.48474       NaN        NaN             0        56      NaN  test
2       37.60684       NaN        NaN             0        56      NaN  test
3       37.24054       NaN        NaN             0        56      NaN  test
4       37.36264       NaN        NaN             0        55      NaN  test
..           ...       ...        ...           ...       ...      ...   ...
188     43.83394       NaN        NaN             0        33      NaN  test
189     44.07814       NaN        NaN             0        55      NaN  test
190     45.12915       NaN        NaN             1        56      NaN  test
191     47.26988       NaN        NaN             1        39      NaN  test
192     45.63972       NaN        NaN             1        53      NaN  test

[193 rows x 12 columns]
                    created_at  entry_id   current    voltage  vibration  \
0    2022-03-15T17:17:51+05:30         1  1.938089  238.64746          0
1    2022-03-15T17:18:07+05:30         2  2.352603  215.62500          0
2    2022-03-15T17:18:24+05:30         3  3.654926  152.06055          0
3    2022-03-15T17:18:41+05:30         4  2.420011  195.74707          0
4    2022-03-15T17:19:00+05:30         5  2.632627  177.10449          0
..                         ...       ...       ...        ...        ...
188  2022-04-05T14:45:50+05:30       189  2.447289  211.85481          0
189  2022-04-05T14:46:06+05:30       190  2.425245  212.24246          0
190  2022-04-05T14:46:22+05:30       191  4.281932  238.45860          0
191  2022-04-05T14:46:38+05:30       192  3.826854  401.23560          0
192  2022-04-05T14:46:54+05:30       193  4.181952  250.38970          0

     temperature  latitude  longitude  relay_status  humidity failure   data
0       37.11844       NaN        NaN             1        25     yes  train
1       37.36264       NaN        NaN             0        25      no  train
2       37.24054       NaN        NaN             0        46      no  train
3       37.11844       NaN        NaN             0        26      no  train
4       37.11844       NaN        NaN             0        26      no  train
..           ...       ...        ...           ...       ...     ...    ...
188     43.83394       NaN        NaN             0        33     NaN   test
189     44.07814       NaN        NaN             0        55     NaN   test
190     45.12915       NaN        NaN             1        56     NaN   test
191     47.26988       NaN        NaN             1        39     NaN   test
192     45.63972       NaN        NaN             1        53     NaN   test

[952 rows x 12 columns]

In [6]:
mt_all.nunique()

created_at      952
entry_id        759
current         952
voltage         943
vibration         2
temperature     142
latitude          0
longitude         0
relay_status      2
humidity         37
failure           2
data              2
dtype: int64

In [7]:
mt_all.head(900)

,created_at,entry_id,current,voltage,vibration,temperature,latitude,longitude,relay_status,humidity,failure,data
0,2022-03-15T17:17:51+05:30,1,1.938089,238.64746,0,37.11844,NaN,NaN,1,25,yes,train
1,2022-03-15T17:18:07+05:30,2,2.352603,215.62500,0,37.36264,NaN,NaN,0,25,no,train
2,2022-03-15T17:18:24+05:30,3,3.654926,152.06055,0,37.24054,NaN,NaN,0,46,no,train
3,2022-03-15T17:18:41+05:30,4,2.420011,195.74707,0,37.11844,NaN,NaN,0,26,no,train
4,2022-03-15T17:19:00+05:30,5,2.632627,177.10449,0,37.11844,NaN,NaN,0,26,no,train
...,...,...,...,...,...,...,...,...,...,...,...,...
136,2022-04-05T14:31:27+05:30,137,2.250655,215.44836,0,41.02564,NaN,NaN,0,53,NaN,test
137,2022-04-05T14:31:44+05:30,138,2.156489,214.47826,0,41.02564,NaN,NaN,0,53,NaN,test
138,2022-04-05T14:32:00+05:30,139,2.405474,215.53758,0,41.02564,NaN,NaN,0,53,NaN,test
139,2022-04-05T14:32:17+05:30,140,1.897152,214.30547,0,40.65934,NaN,NaN,0,53,NaN,test
140,2022-04-05T14:32:33+05:30,141,2.025551,215.45250,0,41.39194,NaN,NaN,0,53,NaN,test

In [8]:
mt_all.drop(['created_at','entry_id','relay_status','longitude','latitude'],axis=1,inplace=True)
mt_all.head()

    current    voltage  vibration  temperature  humidity failure   data
0  1.938089  238.64746          0     37.11844        25     yes  train
1  2.352603  215.62500          0     37.36264        25      no  train
2  3.654926  152.06055          0     37.24054        46      no  train
3  2.420011  195.74707          0     37.11844        26      no  train
4  2.632627  177.10449          0     37.11844        26      no  train

In [9]:
mt_all['vibration']=(mt_all['vibration']==1).astype(int)
mt_all['vibration'].unique()

array([0, 1])

In [10]:
mt_all['failure']=(mt_all['failure']=='yes').astype(int)
#mt_all['failure']=pd.to_numeric(mt_all['failure'],errors='coerce')
mt_all['failure'].unique()

array([1, 0])

In [11]:
mt_all['failure'].unique()
mt_all['current'].unique()

array([ 1.93808893,  2.3526029 ,  3.65492562,  2.42001068,  2.63262665,
        2.59451627,  2.12448554,  2.04803287,  4.60992094,  4.235678  ,
        4.19442425,  0.98371009,  0.78984669,  0.89376661,  0.96982366,
        0.98611527,  0.98802374,  1.15269267,  1.16176723,  0.90221582,
        1.07718469,  1.01017813,  0.81057854,  0.7892283 ,  0.91793953,
        0.80381938,  0.98204515,  0.78887166,  0.68229694,  0.72813621,
        4.32665443,  2.06372241,  1.8968555 ,  1.93466155,  2.40456591,
        1.76934584,  2.24121088,  1.83768597,  1.75239347,  1.98543312,
        1.83967299,  2.0989894 ,  2.28103814,  2.36677188,  2.39966924,
        1.78472824,  2.00175092,  2.29930274,  2.10653765,  2.39657271,
        1.778951  ,  2.41869639,  1.84766263,  1.76742489,  2.28890937,
        2.43990842,  1.98337338,  1.77272241,  2.37758409,  1.80272907,
        2.29976387,  2.08239975,  2.32702776,  1.88560035,  2.24358775,
        2.33664614,  2.38576013,  2.09252737,  2.22348467,  2.03815541,
        2.28596363,  2.29918513,  1.72779129,  1.89996405,  2.10889904,
        1.866281  ,  2.10254092,  2.14774052,  2.42042036,  1.80166287,
        2.19303021,  1.82009469,  1.72426109,  2.21110076,  1.74029539,
        1.98854635,  2.24518528,  1.75275328,  1.81942051,  1.75937541,
        2.42394326,  1.77135936,  2.08430804,  1.98622838,  1.87171033,
        1.9523587 ,  1.80486719,  1.9342348 ,  2.2473578 ,  1.82374295,
        1.88729835,  1.72081884,  1.71985024,  2.40247256,  1.78841191,
        2.16364357,  1.95267162,  1.98246382,  2.17873765,  1.80423727,
        1.95154858,  2.16068202,  1.90336941,  2.01595961,  2.0666578 ,
        1.96387528,  1.96500563,  2.11133672,  2.25658366,  2.22595056,
        2.24078812,  2.22625263,  2.27197232,  2.29603477,  1.95235384,
        1.98929794,  1.98137475,  2.25961197,  2.30013201,  1.84886468,
        1.8189273 ,  1.90062618,  2.32414672,  2.15919794,  2.1645475 ,
        2.38612426,  2.06700417,  1.82379621,  1.77697253,  1.77596364,
        2.39290522,  1.81298577,  2.31241824,  2.32732524,  1.81168615,
        1.87509598,  2.34476284,  1.91156208,  2.4256736 ,  2.45356302,
        1.90770107,  2.43956742,  2.29363061,  2.17690116,  2.47572297,
        2.0495183 ,  2.41420748,  2.44948657,  1.9108993 ,  1.84381728,
        2.25865742,  2.07223475,  1.8240491 ,  2.33670978,  2.04153874,
        1.85760226,  2.29266133,  2.34143003,  1.84272716,  2.47825767,
        2.2756794 ,  1.82850626,  2.07674907,  1.85756947,  2.09140096,
        1.97110963,  2.43332801,  1.77097104,  2.46725878,  2.46176397,
        1.95146599,  1.95308739,  1.88468145,  1.8662237 ,  2.09993288,
        2.36156902,  2.03365047,  2.39657017,  1.90299301,  2.03142706,
        1.80023474,  2.19934072,  1.769421  ,  1.79151225,  2.18621561,
        2.16604523,  1.75056871,  2.00254106,  2.22784972,  1.98141928,
        2.29343635,  2.21298857,  1.86449947,  1.94658647,  1.9312756 ,
        2.33120536,  2.16226593,  2.06779081,  2.31025882,  2.12812237,
        2.21271759,  1.96372495,  2.26130101,  2.17714629,  2.02512168,
        2.36008847,  1.99391325,  2.43902428,  2.43622313,  2.0251872 ,
        1.79184765,  1.77854462,  2.45119259,  2.45864657,  2.14270627,
        1.89863708,  2.29357382,  2.32641218,  2.2389252 ,  1.77886756,
        1.90937267,  1.99275257,  2.4026209 ,  1.9752376 ,  2.14128271,
        2.45841339,  1.92882481,  2.39013214,  2.10506452,  2.02139723,
        1.84399484,  2.32217355,  1.94578564,  2.28550949,  2.00725091,
        2.13689659,  2.09175404,  2.10438618,  2.06940854,  1.7717465 ,
        1.74112051,  2.21866165,  2.0890798 ,  1.907975  ,  1.92264492,
        2.24710524,  2.36556507,  2.37959726,  2.13475034,  2.27967351,
        1.8401663 ,  1.93611259,  2.0791217 ,  1.9619752 ,  2.1738937 ,
        2.38351979,  2.18982567,  1.99328749,  2.29105005,  1.7477705 ,
        1.90907792,  2.14932773,  1.75903707,  2.08390775,  1.7945046 ,
        2.00387453,  1.88797692,  2.36595685,  2.10210038,  2.28156605,
        1.89216041,  2.282022  ,  2.30130176,  2.12007967,  4.20777226,
        4.21130371,  4.53828664,  4.3463092 ,  4.32836408,  4.35238622,
        4.69130986,  2.23731514,  2.23451196,  2.05029526,  2.01286349,
        2.39247874,  1.84143259,  2.0579563 ,  2.46913546,  2.52821528,
        1.90973283,  2.31218964,  2.24985764,  2.48943343,  2.48583394,
        2.08093521,  2.50242566,  1.85213078,  2.49631311,  2.46951429,
        2.508647  ,  1.92508686,  2.22922461,  2.09228953,  1.96310022,
        2.1212496 ,  1.9687233 ,  2.02531007,  1.71906619,  1.7223242 ,
        2.31697188,  2.30801873,  2.01611691,  2.28997131,  2.09626738,
        1.9822582 ,  2.32172373,  2.59855948,  2.15718758,  2.39265075,
        2.26285256,  1.88831766,  2.06509744,  2.12962423,  1.93791683,
        1.95750551,  2.42633461,  2.08901276,  2.14350379,  2.29037618,
        2.50143399,  2.00312392,  2.31107395,  2.04427726,  2.39751909,
        1.95173246,  2.02712187,  2.05232847,  2.5747721 ,  2.12670927,
        2.55215472,  2.1346941 ,  2.36161922,  2.55620945,  2.54257724,
        2.18902654,  1.99901276,  2.22973375,  1.95671468,  1.29637583,
        2.99274802,  2.25826922,  1.90930339,  2.3194991 ,  2.38665111,
        1.8983489 ,  2.13912904,  1.8538869 ,  2.29260559,  2.49739401,
        2.48781396,  1.9053103 ,  1.91201996,  1.99398574,  2.44430122,
        2.17290012,  2.03919758,  1.91572008,  2.14822424,  2.13240198,
        2.30406153,  1.84665212,  2.06730536,  2.11442104,  2.18535125,
        2.05830348,  2.30864117,  2.58446576,  2.50929352,  1.90803096,
        1.87468701,  2.13183573,  2.15659062,  2.27728752,  2.19049535,
        2.59004685,  2.43748575,  2.12085015,  2.59082055,  2.01012505,
        2.1366986 ,  2.28318993,  2.29239681,  2.52943304,  1.96243599,
        2.21441125,  2.1878227 ,  2.42805538,  1.87352523,  2.51278052,
        2.06496707,  1.94343175,  2.5273231 ,  2.30261875,  2.3147119 ,
        2.01479187,  2.01396379,  2.40865781,  1.99270862,  2.5193451 ,
        2.00218988,  2.00698921,  2.48767579,  2.20992174,  2.55620535,
        2.17412272,  1.96248478,  2.31190173,  2.23227603,  1.90116491,
        2.15988662,  2.05496274,  2.12969998,  1.85392763,  1.94156266,
        2.46083255,  2.08040022,  2.46054172,  2.21542842,  1.97292661,
        2.24336969,  2.36943443,  2.13038382,  2.01058358,  2.28244936,
        2.15211586,  2.1172527 ,  2.5356697 ,  1.91194601,  2.20579508,
        2.49393337,  1.89242101,  2.20676366,  2.40182538,  1.96487769,
        1.95103872,  2.03812162,  2.54030136,  2.38108385,  2.20965916,
        2.45492916,  2.34213878,  2.13469692,  1.91118331,  2.17178025,
        2.43010093,  1.91443272,  2.46431584,  2.35866855,  1.83974749,
        2.25960994,  1.84672376,  2.4780248 ,  2.09060133,  2.42970681,
        2.12557081,  1.98393775,  2.04869842,  2.40026413,  2.28579854,
        2.22500576,  2.2380313 ,  2.4100523 ,  2.04996811,  2.07045616,
        2.45721242,  1.89832144,  2.22684604,  1.96702966,  2.3797532 ,
        2.16916114,  2.39099696,  2.39009073,  1.82567471,  1.979595  ,
        2.47281278,  2.0823433 ,  1.89200358,  1.85279179,  2.2429235 ,
        2.04094257,  2.07231826,  2.12234944,  2.22287656,  1.88790245,
        1.87333431,  2.31246523,  2.43448627,  1.95710605,  1.87017009,
        2.22220116,  2.10458123,  2.15528692,  2.46046496,  2.35458244,
        2.05109584,  2.20627734,  2.39650519,  2.19042594,  2.06157413,
        2.21317711,  2.32529407,  2.1232492 ,  1.82144948,  2.02553275,
        1.97975713,  2.00959764,  1.92534182,  1.79969124,  1.90958068,
        1.78798912,  1.8731876 ,  2.04642709,  1.80810191,  2.18175655,
        2.34861539,  2.19593252,  2.20608808,  2.29262009,  1.83520428,
        1.93189421,  2.4035008 ,  1.85061124,  2.51812003,  2.16443699,
        1.97415881,  2.11269607,  1.87329478,  2.26815417,  2.25054906,
        2.43915979,  2.18235629,  2.28126851,  2.50381513,  2.34795183,
        1.93661139,  1.95519136,  1.92050699,  2.04323617,  1.91967944,
        1.86859101,  2.38246643,  2.26273114,  2.02397508,  2.43015099,
        1.80571208,  2.00587781,  2.52717416,  2.12165026,  2.35790106,
        8.69091891,  2.40174433,  1.88865304,  2.37906372,  2.17383453,
        2.51990449,  2.30722516,  1.84805496,  2.12446229,  2.425491  ,
        1.89312709,  2.15270225,  2.04409911,  2.28532969,  2.18117813,
        2.23368374,  1.9949057 ,  2.30471188,  2.06391548,  1.97892492,
        1.82630278,  1.87551739,  2.37168998,  2.32863019,  2.3934591 ,
        1.99250445,  1.90707101,  2.31619029,  2.1267342 ,  1.92750965,
        1.85376542,  1.99136241,  2.23697342,  2.50214079,  2.10117795,
        2.51143902,  2.46024433,  2.52657968,  2.18483521,  2.54038577,
        1.87347381,  2.3337605 ,  2.16480554,  2.53762467,  2.25023165,
        1.94147123,  2.23275677,  1.94839132,  2.01560793,  2.14832562,
        2.52725426,  2.50102619,  2.43674598,  2.11478831,  1.80853043,
        2.45778879,  2.38567633,  2.26486922,  1.87323996,  2.33422571,
        2.42118309,  2.3090744 ,  2.39365097,  2.2717194 ,  1.84642874,
        2.47646105,  2.3736382 ,  2.45539387,  2.2200888 , 26.88866294,
        1.81185902,  2.18715535,  1.79664397,  2.22436998,  2.39107119,
        2.37895824,  2.00180495,  2.37578834,  1.86657667,  2.23673744,
        2.47579137,  2.17429488,  1.95650418,  2.15805219,  2.24078201,
        1.83967169,  1.80694914,  2.39425744,  2.02777784,  2.30137068,
        2.29951406,  2.29163577,  1.7858214 ,  2.09077627,  2.27380998,
        2.42515157,  2.07378018,  1.85550873,  2.32479816,  2.17492888,
        2.3977755 ,  2.26220516,  1.85874288,  2.198013  ,  2.08989475,
        2.2113625 ,  2.35922717,  2.0401346 ,  2.02532131,  1.85892773,
        2.00982868,  2.38260161,  2.0317072 ,  2.18425942,  2.11713355,
        2.03085232,  2.35040168,  1.83190562,  1.79898182,  2.33411948,
        1.98835178,  1.96196158,  2.14291721,  2.43059498,  1.92401511,
        2.51852254,  2.44421023,  2.3703569 ,  2.17349747,  2.15375622,
        2.099052  ,  2.29499291,  2.21181284,  1.98939223,  2.08869389,
        2.48314149,  2.09964537,  2.24905917,  2.01264686,  1.85046956,
        2.08186403,  2.01822227,  1.92550766,  1.87375184,  2.3387792 ,
        1.82414223,  2.43366587,  1.95640316,  2.03235394,  2.29672035,
        2.25635955,  2.05331476,  2.26953208,  1.80318224,  1.96887651,
        2.4411798 ,  2.44099848,  2.45404918,  2.33172925,  2.43177159,
        2.49023768,  1.98428159,  2.03601818,  1.91623573,  2.36969475,
        1.76453275,  1.95030623,  2.07726407,  1.7831457 ,  2.39565346,
        2.11454503,  2.04005051,  2.42754757,  2.47571658,  2.30936256,
        1.93465699,  1.96405179,  2.10042055,  2.37984406,  2.1316445 ,
        2.1123457 ,  1.94796621,  1.76442967,  1.84754025,  2.4523964 ,
        2.29071962,  2.19019978,  2.42712195,  1.91318224,  2.22314817,
        2.21390483,  2.33317695,  2.09708535,  2.24935675,  1.98337197,
        2.18677423,  2.21429825,  2.17472871,  2.29181777,  1.94320984,
        1.96374754,  2.44371651,  1.99043245,  2.30348951,  1.85461184,
        2.20506139,  2.1931113 ,  2.18431039,  1.89633629,  2.12034986,
        1.88136612,  1.80592572,  1.78540835,  2.10618982,  1.8025937 ,
        2.42063958,  2.25279627,  2.10663909,  2.22096179,  2.10421508,
        2.17440237,  2.1051663 ,  2.15791729,  2.10923107,  2.42907389,
        2.42923857,  2.00991796,  1.83018663,  2.35984175,  1.84606982,
        2.08533056,  2.19469373,  1.97518842,  2.15894051,  2.50941999,
        2.33103632,  2.09349872,  2.26196897,  1.99534941,  2.47303572,
        1.91732446,  2.29681498,  2.27597688,  1.93882104,  2.04027529,
        2.3937268 ,  2.15540335,  2.11958207,  2.27313193,  1.93566008,
        2.06922985,  2.31123551,  1.81772555,  2.43090333,  2.24741052,
        1.85632882,  2.4191657 ,  1.84078027,  1.80799073,  2.24640308,
        2.493824  ,  2.19469069,  2.21703484,  2.2741751 ,  1.82817298,
        2.16897321,  2.41653386,  2.41504846,  1.85744896,  2.45333628,
        2.04117258,  2.32832822,  2.38993846,  1.93252962,  2.28199638,
        2.41192617,  2.02088826,  2.06830911,  1.83117423,  2.44387676,
        2.00417072,  2.18353073,  1.91262391,  1.99866536,  2.30654065,
        2.10062228,  1.99661252,  2.19162145,  2.19352985,  2.17482057,
        1.83510502,  1.94154006,  2.07425171,  1.92113178,  2.19672131,
        1.88196549,  2.54343827,  2.28330668,  2.14962754,  2.48502322,
        2.01739394,  1.87976964,  2.20949977,  2.34320736,  2.467282  ,
        1.89352361,  2.12303496,  1.93451587,  2.43712081,  1.96311885,
        1.92782504,  2.4385614 ,  1.96210035,  1.95074618,  1.99932798,
        2.31425113,  2.0512744 ,  2.25806871,  1.89637934,  2.1136962 ,
        2.15180157,  2.19120433,  2.2683353 ,  2.12925006,  1.88812924,
        2.25065533,  2.15648896,  2.40547379,  1.89715176,  2.02555087,
        1.8415707 ,  1.93048033,  2.17385608,  1.85990993,  2.59307401,
        2.02208327,  2.2611759 ,  1.90334454,  2.00461246,  2.03959443,
        2.22013675,  2.11162675,  1.85877467,  1.84688795,  2.30092733,
        2.05159223,  2.03180993,  1.94309263,  2.12313296,  2.43606524,
        2.43238996,  1.98309003,  2.43233224,  2.22132987,  2.48931235,
        1.89650249,  2.3088743 ,  2.12299544,  2.54638819,  2.41053937,
        2.07309294,  2.18548684,  2.23655142,  2.1809931 ,  2.25024025,
        2.52535285,  2.28880222,  2.20036825,  2.08119351,  1.93038195,
        2.48863386,  2.3661077 ,  2.55487003,  2.01781396,  2.61737917,
        2.09677871,  2.23300745,  2.44728925,  2.42524517,  4.281932  ,
        3.826854  ,  4.181952  ])

In [13]:
for col in mt_all.columns:
    if col=='data' or mt_all[col].isnull().sum()==0:continue
    mt_all.loc[mt_all[col].isnull(),col]=mt_all.loc[mt_all['data']=='train',col].mean()
print(mt_all.head(900))

      current    voltage  vibration  temperature  humidity  failure   data
0    1.938089  238.64746          0     37.11844        25        1  train
1    2.352603  215.62500          0     37.36264        25        0  train
2    3.654926  152.06055          0     37.24054        46        0  train
3    2.420011  195.74707          0     37.11844        26        0  train
4    2.632627  177.10449          0     37.11844        26        0  train
..        ...        ...        ...          ...       ...      ...    ...
136  2.250655  215.44836          0     41.02564        53        0   test
137  2.156489  214.47826          0     41.02564        53        0   test
138  2.405474  215.53758          0     41.02564        53        0   test
139  1.897152  214.30547          0     40.65934        53        0   test
140  2.025551  215.45250          0     41.39194        53        0   test

[900 rows x 7 columns]

In [44]:
mt_train = mt_all[mt_all['data']=='train']

del mt_train['data']



mt_test = mt_all[mt_all['data']=='test']

print(mt_test)



mt_test.drop(['data','failure'],axis=1,inplace=False)

print(mt_test)

      current    voltage  vibration  temperature  humidity  failure  data
0    2.223148  223.14752          0     37.36264        56        0  test
1    2.213905  224.07919          0     37.48474        56        0  test
2    2.333177  223.81500          0     37.60684        56        0  test
3    2.097085  224.11105          0     37.24054        56        0  test
4    2.249357  223.86400          0     37.36264        55        0  test
..        ...        ...        ...          ...       ...      ...   ...
188  2.447289  211.85481          0     43.83394        33        0  test
189  2.425245  212.24246          0     44.07814        55        0  test
190  4.281932  238.45860          0     45.12915        56        0  test
191  3.826854  401.23560          0     47.26988        39        0  test
192  4.181952  250.38970          0     45.63972        53        0  test

[193 rows x 7 columns]
      current    voltage  vibration  temperature  humidity  failure  data
0    2.223148  223.14752          0     37.36264        56        0  test
1    2.213905  224.07919          0     37.48474        56        0  test
2    2.333177  223.81500          0     37.60684        56        0  test
3    2.097085  224.11105          0     37.24054        56        0  test
4    2.249357  223.86400          0     37.36264        55        0  test
..        ...        ...        ...          ...       ...      ...   ...
188  2.447289  211.85481          0     43.83394        33        0  test
189  2.425245  212.24246          0     44.07814        55        0  test
190  4.281932  238.45860          0     45.12915        56        0  test
191  3.826854  401.23560          0     47.26988        39        0  test
192  4.181952  250.38970          0     45.63972        53        0  test

[193 rows x 7 columns]

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
params = {'class_weight':['balanced'],'penalty':['l1','l2'],
         'C':np.linspace(0.0001,1000,10)}

In [65]:
model = LogisticRegression(fit_intercept=True,solver='lbfgs', max_iter=3000)

In [66]:
from sklearn.model_selection import GridSearchCV

In [83]:
grid_search = GridSearchCV(model,param_grid=params,cv=10,scoring='roc_auc',n_jobs=-1)

In [84]:
x_train = mt_train.drop('failure',axis=1)
y_train = mt_train['failure']

print(x_train)
print(y_train)

      current    voltage  vibration  temperature  humidity
0    1.938089  238.64746          0     37.11844        25
1    2.352603  215.62500          0     37.36264        25
2    3.654926  152.06055          0     37.24054        46
3    2.420011  195.74707          0     37.11844        26
4    2.632627  177.10449          0     37.11844        26
..        ...        ...        ...          ...       ...
754  2.452396  223.58131          0     37.48474        56
755  2.290720  223.07837          0     37.11844        56
756  2.190200  223.09837          0     37.72894        56
757  2.427122  222.83594          0     37.11844        56
758  1.913182  222.25797          0     37.97314        56

[759 rows x 5 columns]
0      1
1      0
2      0
3      0
4      0
      ..
754    0
755    0
756    0
757    0
758    0
Name: failure, Length: 759, dtype: int32

In [85]:
grid_search.fit(x_train,y_train)

C:\Users\harsh\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.82535887        nan 0.98152174        nan 0.98223602
        nan 0.98271222        nan 0.98271222        nan 0.98271222
        nan 0.98271222        nan 0.98271222        nan 0.98271222
        nan 0.98271222]
  warnings.warn(

GridSearchCV(cv=10, estimator=LogisticRegression(max_iter=3000), n_jobs=-1,
             param_grid={'C': array([1.000000e-04, 1.111112e+02, 2.222223e+02, 3.333334e+02,
       4.444445e+02, 5.555556e+02, 6.666667e+02, 7.777778e+02,
       8.888889e+02, 1.000000e+03]),
                         'class_weight': ['balanced'],
                         'penalty': ['l1', 'l2']},
             scoring='roc_auc')

In [86]:
grid_search.best_estimator_

LogisticRegression(C=333.3334, class_weight='balanced', max_iter=3000)

In [87]:
mt_train['failure'].nunique()
grid_search.cv_results_

{'mean_fit_time': array([0.00102687, 0.0172116 , 0.00088763, 0.04241464, 0.00080051,
        0.05550973, 0.00156243, 0.05501366, 0.00156236, 0.05799217,
        0.00599656, 0.05616353, 0.        , 0.06155686, 0.00202382,
        0.05742133, 0.00156248, 0.0640573 , 0.00236297, 0.07508271]),
 'std_fit_time': array([0.00030477, 0.00242788, 0.00030182, 0.00747899, 0.00240154,
        0.01553777, 0.00468729, 0.01705879, 0.00468707, 0.01618847,
        0.01360117, 0.01278714, 0.        , 0.00470169, 0.00459365,
        0.01826733, 0.00468743, 0.02099595, 0.0050233 , 0.0184654 ]),
 'mean_score_time': array([0.        , 0.00384452, 0.        , 0.00156236, 0.        ,
        0.0059516 , 0.        , 0.00309825, 0.        , 0.00453343,
        0.        , 0.00598793, 0.        , 0.00403233, 0.        ,
        0.00333815, 0.        , 0.00353243, 0.        , 0.00368559]),
 'std_score_time': array([0.        , 0.00164984, 0.        , 0.00468707, 0.        ,
        0.00965829, 0.        , 0.00551468, 0.        , 0.006971  ,
        0.        , 0.00656263, 0.        , 0.00536398, 0.        ,
        0.00513989, 0.        , 0.00484787, 0.        , 0.00077752]),
 'param_C': masked_array(data=[0.0001, 0.0001, 111.11120000000001, 111.11120000000001,
                    222.22230000000002, 222.22230000000002, 333.3334,
                    333.3334, 444.4445, 444.4445, 555.5556, 555.5556,
                    666.6667, 666.6667, 777.7778000000001,
                    777.7778000000001, 888.8889, 888.8889, 1000.0, 1000.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_class_weight': masked_array(data=['balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_penalty': masked_array(data=['l1', 'l2', 'l1', 'l2', 'l1', 'l2', 'l1', 'l2', 'l1',
                    'l2', 'l1', 'l2', 'l1', 'l2', 'l1', 'l2', 'l1', 'l2',
                    'l1', 'l2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.0001, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 0.0001, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 111.11120000000001, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 111.11120000000001, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 222.22230000000002, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 222.22230000000002, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 333.3334, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 333.3334, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 444.4445, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 444.4445, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 555.5556, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 555.5556, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 666.6667, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 666.6667, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 777.7778000000001, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 777.7778000000001, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 888.8889, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 888.8889, 'class_weight': 'balanced', 'penalty': 'l2'},
  {'C': 1000.0, 'class_weight': 'balanced', 'penalty': 'l1'},
  {'C': 1000.0, 'class_weight': 'balanced', 'penalty': 'l2'}],
 'split0_test_score': array([       nan, 0.99585921,        nan, 0.99378882,        nan,
        0.99378882,        nan, 0.99378882,        nan, 0.99378882,
               nan, 0.99378882,        nan, 0.99378882,        nan,
        0.99378882,        nan, 0.99378882,        nan, 0.99378882]),
 'split1_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,
         1., nan,  1., nan,  1., nan,  1.]),
 'split2_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,
         1., nan,  1., nan,  1., nan,  1.]),
 'split3_test_score': array([       nan, 0.73809524,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ,
               nan, 1.        ,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ]),
 'split4_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,
         1., nan,  1., nan,  1., nan,  1.]),
 'split5_test_score': array([       nan, 0.98571429,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ,
               nan, 1.        ,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ]),
 'split6_test_score': array([       nan, 0.98571429,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ,
               nan, 1.        ,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ]),
 'split7_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,  1., nan,
         1., nan,  1., nan,  1., nan,  1.]),
 'split8_test_score': array([       nan, 0.50714286,        nan, 0.98809524,        nan,
        0.9952381 ,        nan, 1.        ,        nan, 1.        ,
               nan, 1.        ,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ,        nan, 1.        ]),
 'split9_test_score': array([       nan, 0.0410628 ,        nan, 0.83333333,        nan,
        0.83333333,        nan, 0.83333333,        nan, 0.83333333,
               nan, 0.83333333,        nan, 0.83333333,        nan,
        0.83333333,        nan, 0.83333333,        nan, 0.83333333]),
 'mean_test_score': array([       nan, 0.82535887,        nan, 0.98152174,        nan,
        0.98223602,        nan, 0.98271222,        nan, 0.98271222,
               nan, 0.98271222,        nan, 0.98271222,        nan,
        0.98271222,        nan, 0.98271222,        nan, 0.98271222]),
 'std_test_score': array([       nan, 0.30438346,        nan, 0.04954152,        nan,
        0.04968244,        nan, 0.04982738,        nan, 0.04982738,
               nan, 0.04982738,        nan, 0.04982738,        nan,
        0.04982738,        nan, 0.04982738,        nan, 0.04982738]),
 'rank_test_score': array([20, 10, 17,  9, 14,  8, 19,  1, 11,  1, 13,  1, 15,  1, 16,  1, 18,
         1, 12,  1])}

In [88]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.6f} (std: {1:.6f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [89]:
report(grid_search.cv_results_,3)

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 333.3334, 'class_weight': 'balanced', 'penalty': 'l2'}

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 444.4445, 'class_weight': 'balanced', 'penalty': 'l2'}

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 555.5556, 'class_weight': 'balanced', 'penalty': 'l2'}

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 666.6667, 'class_weight': 'balanced', 'penalty': 'l2'}

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 777.7778000000001, 'class_weight': 'balanced', 'penalty': 'l2'}

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 888.8889, 'class_weight': 'balanced', 'penalty': 'l2'}

Model with rank: 1
Mean validation score: 0.982712 (std: 0.049827)
Parameters: {'C': 1000.0, 'class_weight': 'balanced', 'penalty': 'l2'}

In [92]:
print(mt_test)
test_prediction = grid_search.predict_proba(mt_test)

      current    voltage  vibration  temperature  humidity  failure  data
0    2.223148  223.14752          0     37.36264        56        0  test
1    2.213905  224.07919          0     37.48474        56        0  test
2    2.333177  223.81500          0     37.60684        56        0  test
3    2.097085  224.11105          0     37.24054        56        0  test
4    2.249357  223.86400          0     37.36264        55        0  test
..        ...        ...        ...          ...       ...      ...   ...
188  2.447289  211.85481          0     43.83394        33        0  test
189  2.425245  212.24246          0     44.07814        55        0  test
190  4.281932  238.45860          0     45.12915        56        0  test
191  3.826854  401.23560          0     47.26988        39        0  test
192  4.181952  250.38970          0     45.63972        53        0  test

[193 rows x 7 columns]

ValueError: could not convert string to float: 'test'

In [93]:
test_prediction

NameError: name 'test_prediction' is not defined

In [22]:
grid_search.classes_

AttributeError: 'LogisticRegression' object has no attribute 'classes_'

In [23]:
train_score=grid_search.predict_proba(x_train)[:,1]
real = y_train

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [24]:
cutoffs = np.linspace(.001,0.999, 999)

In [25]:
import seaborn as sns

In [26]:
 KS=[]

In [27]:
for cutoff in cutoffs:
 predicted=(train_score>cutoff).astype(int)
 TP=((real==1)&(predicted==1)).sum()
 FP=((real==0)&(predicted==1)).sum()
 TN=((real==0)&(predicted==0)).sum()
 FN=((real==1)&(predicted==0)).sum()
 
 ks=(TP/(TP+FN))-(FP/(TN+FP))
 KS.append(ks)

temp=pd.DataFrame({'cutoffs':cutoffs,'KS':KS})
sns.lmplot(x='cutoffs',y='KS',data=temp,fit_reg=False)

NameError: name 'train_score' is not defined

In [28]:
 ks

NameError: name 'ks' is not defined

In [29]:
test_hard_classes=(test_prediction>cutoffs[KS==max(KS)][0]).astype(int)

NameError: name 'test_prediction' is not defined

In [30]:
test_hard_classes

NameError: name 'test_hard_classes' is not defined

In [31]:
pd.DataFrame(test_hard_classes).to_csv("mysubmissionelogistic.csv",index=False)

NameError: name 'test_hard_classes' is not defined